// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using N_Tier_Architecture_DataAccess.Data;

#nullable disable

namespace N_Tier_Architecture.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250326232620_productadded")]
    partial class productadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("N_Tier_Architecture_Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Story"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fiction"
                        });
                });

            modelBuilder.Entity("N_Tier_Architecture_Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "An exciting action-packed game.",
                            ImageUrl = "imageUrl1.jpg",
                            Name = "Action Game 1",
                            Price = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Another action-packed game.",
                            ImageUrl = "imageUrl2.jpg",
                            Name = "Action Game 2",
                            Price = 60
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "A compelling storybook for children.",
                            ImageUrl = "imageUrl3.jpg",
                            Name = "Story Book 1",
                            Price = 20
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "A thrilling fiction novel.",
                            ImageUrl = "imageUrl4.jpg",
                            Name = "Fiction Novel 1",
                            Price = 30
                        });
                });

            modelBuilder.Entity("N_Tier_Architecture_Models.Product", b =>
                {
                    b.HasOne("N_Tier_Architecture_Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
